---
title: "Run scoring trends - references"
author: "Martin Monkman"
date: "Wednesday, November 12, 2014"
output: html_document
---

## Major League Baseball run scoring trends
### Version 3.01 (2015-02-21)
### Documentation

This app was written by Martin Monkman using the R package [Shiny](http://shiny.rstudio.com/).

The app is on [shinyapps.io by RStudio](https://www.shinyapps.io/).   

All of the files associated with this app, including the code and R markdown files, can be found on [github.com](github.com), 
at [MonkmanMH/MLBrunscoring_shiny](https://github.com/MonkmanMH/MLBrunscoring_shiny).


### References

**Data Source**

The data for this app comes from the 'Teams' table in the Lahman database [www.seanlahman.com/baseball-archive/statistics/](http://www.seanlahman.com/baseball-archive/statistics/).

And yes, I know there's a [`Lahman` package](http://cran.r-project.org/web/packages/Lahman/index.html) in R (I'm one of the contributors!)  But as I note below ("Summarizing the source data"), in an application setting, it's more efficient to do some of the data manipulation prior to running the app--why make the user wait for tasks that need to be run each and every time?  


**shiny**:  the RStudio site provides a wealth of materials for Shiny developers.

+ [tutorial](http://shiny.rstudio.com/tutorial/) -- a great place if you're new to Shiny, but a useful reference if you are looking for code examples too.
+ [The Shiny cheat sheet](http://shiny.rstudio.com/articles/cheatsheet.html) -- once you are rolling, this is a handy reference to have on your desk.
+ [widget gallery](http://shiny.rstudio.com/gallery/widget-gallery.html) -- with the wide range of UI widgets within Shiny, each with a variety of options, this gallery is an amazing resource.
+ [function reference](http://shiny.rstudio.com/reference/shiny/latest/) -- just like it says. Essential.  


**shiny - other sources**

+ [shiny tutorial using Gapminder data](https://stat545-ubc.github.io/shiny03_activity.html) -- a tutorial from the UBC course Stat 545 by Julia Gustavsen.


**dplyr**

+ [Introduction to dplyr](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html)

+ [Hands-on dplyr tutorial for faster data manipulation in R](http://www.dataschool.io/dplyr-tutorial-for-faster-data-manipulation-in-r/)

+ [on joins](http://stackoverflow.com/questions/1299871/how-to-join-data-frames-in-r-inner-outer-left-right)


### Summarizing the source data ###

What follows is a short set of R instructions that takes the "Teams" table in the Lahman database and summarizes it for the Shiny run scoring app. (Note that I renamed the original CSV file "Teams_2014.csv" for this exercise.)

Thus rather than having the app: 

1. remove unnecessary records (rows) and fields (columns), and

2. run the calculations for the runs-per-game, runs-allowed-per-game, and indexed versions of those

the calculations are conducted beforehand, and the subsequent tables (saved as CSV files) are read into the app.

The original version of the app loaded the `Lahman` package and did the same summarization after the application was launched.  By doing the summarization prior to running the app, there are quantifiable improvements in the performance of the app.

```{r, eval=FALSE}
# package load 
library(dplyr)
library(reshape)
library(ggplot2)
#

# CREATE LEAGUE SUMMARY TABLES
# ============================
#
# load the Lahman data table "Teams", filter
Teams <- read.csv("Teams_2014.csv", header=TRUE)

# select a sub-set of teams from 1901 [the establishment of the American League] forward to most recent year
LG_RPG <- Teams %>%
  filter(yearID > 1900, lgID != "FL") %>%
  group_by(yearID, lgID) %>%
  summarise(R=sum(R), RA=sum(RA), G=sum(G)) %>%
  mutate(leagueRPG=R/G, leagueRAPG=RA/G)
head(LG_RPG)
#
# and a version with just the MLB totals
MLB_RPG <- Teams %>%
  filter(yearID > 1900, lgID != "FL") %>%
  group_by(yearID) %>%
  summarise(R=sum(R), RA=sum(RA), G=sum(G)) %>%
  mutate(leagueRPG=R/G, leagueRAPG=RA/G)
head(MLB_RPG)
#
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# create data frame Teams.merge with league averages
Teams.merge <-  Teams %>%
  mutate(teamRPG=(R/G), teamRAPG=(RA/G), WLpct=(W/G)) 
Teams.merge <- 
  merge(Teams.merge, LG_RPG, by = c("yearID", "lgID"))
#
# create new values to compare the individual team's runs/game compares to the league average that season
Teams.merge <- Teams.merge %>%
  # runs scored index where 100=the league average for that season
  mutate(R_index = (teamRPG/leagueRPG)*100) %>%
  mutate(R_index.sd = sd(R_index)) %>%
  mutate(R_z = (R_index - 100)/R_index.sd) %>%
  # runs allowed
  mutate(RA_index = (teamRAPG/leagueRAPG)*100) %>%
  mutate(RA_index.sd = sd(RA_index)) %>%
  mutate(RA_z = (RA_index - 100)/RA_index.sd)
#
head(LG_RPG)
head(MLB_RPG)
head(Teams.merge)
#
# round values for data display (is there any way to do this as a listed batch?)
LG_RPG$leagueRPG <- round(LG_RPG$leagueRPG, 2)  
LG_RPG$leagueRAPG <- round(LG_RPG$leagueRAPG, 2)  
#
MLB_RPG$leagueRPG <- round(MLB_RPG$leagueRPG, 2)  
MLB_RPG$leagueRAPG <- round(MLB_RPG$leagueRAPG, 2)  
#
Teams.merge$R_index <- round(Teams.merge$R_index, 2)  
Teams.merge$R_index.sd <- round(Teams.merge$R_index.sd, 2)  
Teams.merge$R_z <- round(Teams.merge$R_z, 2)  
Teams.merge$RA_index <- round(Teams.merge$RA_index, 2)  
Teams.merge$RA_index.sd <- round(Teams.merge$RA_index.sd, 2)  
Teams.merge$RA_z <- round(Teams.merge$RA_z, 2)  
Teams.merge$teamRPG <- round(Teams.merge$teamRPG, 2)  
Teams.merge$teamRAPG <- round(Teams.merge$teamRAPG, 2)  
Teams.merge$leagueRPG <- round(Teams.merge$leagueRPG, 2)  
Teams.merge$leagueRAPG <- round(Teams.merge$leagueRAPG, 2)  
Teams.merge$WLpct <- round(Teams.merge$WLpct, 3)  

head(LG_RPG)
head(MLB_RPG)
head(Teams.merge)


write.csv(LG_RPG, file="LG_RPG.csv", row.names=FALSE)
write.csv(MLB_RPG, file="MLB_RPG.csv", row.names=FALSE)
write.csv(Teams.merge, file="Teams_merge.csv", row.names=FALSE)
```


*-30-*
