---
title: "Run scoring trends - references"
author: "Martin Monkman"
date: "Wednesday, November 12, 2014"
output: html_document
---

### Major League Baseball run scoring trends
#### Version 1 (2014-11-12)

This app was written using [Shiny](http://shiny.rstudio.com/) by Martin Monkman.

Future versions will contain:

* A direct comparison of the trends in each league
* Individual team scoring trends

All of the files associated with this app can be found on [github.com](github.com), 
at [MonkmanMH/MLBrunscoring_shiny](https://github.com/MonkmanMH/MLBrunscoring_shiny).


#### bayesball.blogspot.com

Earlier versions of my analysis of run scoring trends in Major League Baseball can be found on my blog bayesball.blogspot.com.  In reverse order of publication, they are:

* ["Major League Baseball run scoring trends with R's Lahman package"](http://bayesball.blogspot.ca/2013/06/major-league-baseball-run-scoring.html), 2014-06-04
* ["MLB runs allowed by team; Or, How good were the Maddux/Glavine-era Braves?"](http://bayesball.blogspot.ca/2013/02/mlb-runs-allowed-by-team.html), 2014-02-24
* ["Run production, one team at a time"](http://bayesball.blogspot.ca/2013/02/run-production-one-team-at-time.html), 2013-02-17
* ["Comparing individual team run production; Or, The 2010 Mariners: How Bad Were They?"](http://bayesball.blogspot.ca/2013/02/comparing-individual-team-run-production.html), 2013-02-02
* ["Trends in run scoring - comparing the leagues"](http://bayesball.blogspot.ca/2012/08/trends-in-run-scoring-comparing-leagues.html), 2012-08-10
* ["Trends in run scoring, NL edition (more R)"](http://bayesball.blogspot.ca/2012/07/trends-in-run-scoring-nl-edition-more-r.html), 2012-07-17
* ["Trends in AL run scoring (using R)"](http://bayesball.blogspot.ca/2012/07/trends-in-al-run-scoring-using-r.html), 2012-07-14

#### References

* The RStudio site provides a wealth of materials for Shiny developers.

+ [tutorial](http://shiny.rstudio.com/tutorial/) -- a great place if you're new to Shiny, but a useful reference if you are looking for code examples too.
+ [The Shiny cheat sheet](http://shiny.rstudio.com/articles/cheatsheet.html) -- once you are rolling, this is a handy reference to have on your desk.
+ [widget gallery](http://shiny.rstudio.com/gallery/widget-gallery.html) -- with the wide range of UI widgets within Shiny, each with a variety of options, this gallery is an amazing resource.
+ [function reference](http://shiny.rstudio.com/reference/shiny/latest/) -- just like it says. Essential.


*-30-*
