---
title: "Runs per game by MLB team: a first Shiny app"
author: "Martin Monkman"
date: "Sunday, November 09, 2014"
output: html_document
---

#### RETRACING MY STEPS

As I've been learning the functionality of Shiny, the web app for R, I have worked my way through the helpful [tutorials available from the developers at RStudio](http://shiny.rstudio.com/tutorial/). At some point, though, one needs to break out and develop one's own application.

Ta-da! [MLB run scoring trends](https://monkmanmh.shinyapps.io/MLBrunscoring_shiny/).

This Shiny app is a return to my earlier analysis on run scoring trends in Major League Baseball, last seen in my blog post ["Major League Baseball run scoring trends with R's Lahman package"](http://bayesball.blogspot.ca/2013/06/major-league-baseball-run-scoring.html). This project gave me the opportunity to update the underlying data, as well as to introduce some of the coding improvements I've learned along the way (notably the packages `ggplot2` and `dplyr`.)

**Some notable changes in the code:**

* In the original version ([starting here](http://bayesball.blogspot.ca/2012/07/trends-in-al-run-scoring-using-r.html)), I treated each league separately, starting with subsetting (now, with `dplr`, filtering) the Lahman "Teams" table on the `lgID` variable into two separate data frames which were then used to separately generate the two charts. Now, with `ggplot2`, I have given the reader the option of making that split or not; the code uses the faceting option to plot the two leagues. This is both more flexible from the reader's point of view, and more efficient code.

* In my original approach, the trend lines were generated using the `loess` function, embedded in a discrete object, and then added to the plot as a separately plotted `line`.  By using `ggplot2`, a LOESS trendline can be quickly added to the plot call with the `stat_smooth()` option, a much more efficient approach.

* The `stat_smooth()` option makes it possible to adjust the degree of smoothing of the tend line through changes to the `span` specification. Originally this was hard-coded, but is now dynamic, controlled in the Shiny app through a slider widget.

* The `stat_smooth()` also includes the option of showing a confidence interval. This is achieved through the `level` specification. For this, I used a set of radio buttons in the Shiny user interface. (I had initially tried a slider, but was not able to specify a set of pre-defined points for the confidence intervals.)

* The start and end dates of the plots are also user-controlled through a slider widget. You will notice that the date in the chart title changes along with the range of the plot. The time range, once less than the full range, can be animated and rolls back to 1901 and then forward, preserving the length of the time span.

**Other things I learned:**

* Radio buttons return factors, even if they look numeric in the ui.r code. In order to get the values that are input by the user to work in the `stat_smooth()`, I wrapped them in `as.numeric()`.

* I already knew that I was struggling to keep up with the changes in the R coding environment, but this exercise opened my eyes to even more potential opportunities. The latest version of Shiny (0.10) added a lot of new functionality, but I hadn't realized the degree of integration with other visualization tools. This recent blog entry, ["Goodbye static graphs, hello shiny, ggvis, rmarkdown"](http://jackman.stanford.edu/blog/?p=2892) by Simon Jackman, gives some hints as to where an integrated analytic & reporting environment might go.  Exciting stuff, indeed.  

**Next steps**

* The original analysis had a comparison of the two leagues, with them plotted on the same chart. This is in many ways preferable to the faceting, particularly the chart where I plotted the absolute difference (rather than the raw scores side-by-side).

* Adding the option to plot the runs scored and runs allowed by each team, as I did in this blog post [here](http://bayesball.blogspot.ca/2013/02/run-production-one-team-at-time.html) and [here](http://bayesball.blogspot.ca/2013/02/mlb-runs-allowed-by-team.html).

* This version has a short "references" page. I will be adding a "documentation" tab, which will include an [R Markdown](http://rmarkdown.rstudio.com/) document with an annotated version of the Shiny code.

I am always open to suggestions -- feel free to comment on the Shiny app [MLB run scoring trends](https://monkmanmh.shinyapps.io/MLBrunscoring_shiny/) in the comments below.

-30-