## Major League Baseball run scoring trends
### Version 3.03 (2015-03-01)
### Documentation

This app was written by Martin Monkman using the R package [Shiny](http://shiny.rstudio.com/).

The app is on [shinyapps.io by RStudio](https://www.shinyapps.io/).   

All of the files associated with this app, including the code and R markdown files, can be found on [github.com](github.com), 
at [MonkmanMH/MLBrunscoring_shiny](https://github.com/MonkmanMH/MLBrunscoring_shiny).


### References

**Data Source**

The data for this app comes from the 'Teams' table in the Lahman database [www.seanlahman.com/baseball-archive/statistics/](http://www.seanlahman.com/baseball-archive/statistics/).

And yes, I know there's a [`Lahman` package](http://cran.r-project.org/web/packages/Lahman/index.html) in R (I'm one of the contributors!)  But in an application setting, it's more efficient (for both the system and the user) to have the app reference only the data values necessary for the application, rather than re-running tasks that would be needed each and every time. A complete account, including the code, of the data summarization can be found in the github repository, in the file `MLBrunscoring_summarytables.Rmd`. 


**shiny**:  the RStudio site provides a wealth of materials for Shiny developers.

+ [tutorial](http://shiny.rstudio.com/tutorial/) -- a great place if you're new to Shiny, but a useful reference if you are looking for code examples too.
+ [The Shiny cheat sheet](http://shiny.rstudio.com/articles/cheatsheet.html) -- once you are rolling, this is a handy reference to have on your desk.
+ [widget gallery](http://shiny.rstudio.com/gallery/widget-gallery.html) -- with the wide range of UI widgets within Shiny, each with a variety of options, this gallery is an amazing resource.
+ [function reference](http://shiny.rstudio.com/reference/shiny/latest/) -- just like it says. Essential.  


**shiny - other sources**

+ [shiny tutorial using Gapminder data](https://stat545-ubc.github.io/shiny03_activity.html) -- a tutorial from the UBC course Stat 545 by Julia Gustavsen.


**dplyr**

+ [Introduction to dplyr](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html)

+ [Hands-on dplyr tutorial for faster data manipulation in R](http://www.dataschool.io/dplyr-tutorial-for-faster-data-manipulation-in-r/)

+ [on joins](http://stackoverflow.com/questions/1299871/how-to-join-data-frames-in-r-inner-outer-left-right)



*-30-*
